version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: lasereyes
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      COINOS_URL: ${COINOS_URL:-https://coinos.io}
      COINOS_API_KEY: ${COINOS_API_KEY}
      CHARGE_AMOUNT: ${CHARGE_AMOUNT:-150}
      CHARGE_MEMO: ${CHARGE_MEMO:-Laser eyes download}
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: lasereyes
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db-data:
